# Generated by Django 5.1.7 on 2025-04-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='d0c_image',
            new_name='doc_image',
        ),
    ]
